[package]
name = "mprd-risc0-shared"
version = "0.1.0"
edition = "2021"
description = "Shared types between MPRD Risc0 guest and host"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
